name: Sync GitLab to GitHub

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Pull latest changes from GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.kit.edu/haoran.yu/mf-system.git
          git fetch gitlab
          git merge gitlab/main --allow-unrelated-histories -m "Sync GitLab to GitHub"
          git push origin main
